apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: academia-logika-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0m"
spec:
  ingressClassName: nginx
  rules:
    - host: academialogika.com
      http:
        paths:
          - path: /_next
            pathType: Prefix
            backend:
              service:
                name: academia-logika-svc
                port:
                  number: 80

          - path: /
            pathType: Prefix
            backend:
              service:
                name: academia-logika-svc
                port:
                  number: 80
